Document: libucl
Title: Debian libucl Manual
Author: <insert document author here>
Abstract: This manual describes what libucl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libucl/libucl.sgml.gz

Format: postscript
Files: /usr/share/doc/libucl/libucl.ps.gz

Format: text
Files: /usr/share/doc/libucl/libucl.text.gz

Format: HTML
Index: /usr/share/doc/libucl/html/index.html
Files: /usr/share/doc/libucl/html/*.html
